version: '3.8'

services:
  web:
    image: nginx:1.21.6
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - web_network

  db:
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    networks:
      - db_network

  app:
    image: myapp:1.0.0
    environment:
      - APP_ENV=development
      - DATABASE_URL=mysql://user:password@db:3306/testdb
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "python", "app.py"]
    secrets:
      - db_password
    networks:
      - app_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
  app_network:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
