name: Good Practices Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build step
        run: |
          echo "Building application..."
          echo "Build complete!"

  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install pytest
        run: pip install pytest

      - name: Run unit tests
        run: pytest lab4/tests

  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Deploy step
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          echo "Deploying application..."
          echo "Using secret: $SECRET_TOKEN"

  notify_build:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Notify build complete
        run: echo "Build completed successfully!"

  notify_tests:
    runs-on: ubuntu-20.04
    needs: [unit_tests]
    steps:
      - name: Notify tests complete
        run: echo "Tests completed successfully!"

  notify_deploy:
    runs-on: ubuntu-20.04
    needs: [deploy]
    steps:
      - name: Notify deploy complete
        run: echo "Deploy completed successfully!"
