name: Good Practices Workflow

on:
  push:
    branches:
      - main

jobs:
  # хорошая практика №1: версионирование образа
  build:
    runs-on: ubuntu-20.04  # указываем конкретную версию образа
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build step
        run: |
          echo "Building application..."
          # Здесь мог бы быть реальный процесс сборки

  # хорошая практика №2: выполнение тестов
  unit_tests:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # используем конкретную версию Python

      - name: Install pytest
        run: pip install pytest

      - name: Run unit tests
        run: pytest lab4/tests/

  # хорошая практика №3: безопасное хранение секретов
  deploy:
    runs-on: ubuntu-20.04
    needs: unit_tests  # выполняем деплой только после успешного прохождения тестов
    steps:
      - name: Deploy step
        env:  # используем секреты, хранящиеся в безопасном месте (в нашем случае - GitHub Secrets)
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          echo "Deploying application..."
          echo "Using secret: $SECRET_TOKEN"
          # Здесь мог бы быть реальный процесс деплоя

  # хорошая практика №5: параллельное выполнение процессов
  notify:
    runs-on: ubuntu-20.04
    needs: [build, unit_tests, deploy]  # уведомления запускаются после всех этапов
    steps:
      - name: Send notifications
        run: |
          echo "Sending notification about the status of the workflow..."
          echo "Build, tests, and deployment have completed successfully."

  # хорошая практика №4: уведомления
  # этот шаг включён в задачу `notify` для уведомления разработчиков
